# Generated by Django 5.1.6 on 2025-02-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=64)),
                ('author', models.CharField(blank=True, max_length=64, null=True)),
                ('book_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'book',
                'managed': False,
            },
        ),
    ]
